#
# Ansible Playbook for removing Magento 2
#
# Readme:
#   1. Add the hosts you want to run this Playbook on to Ansible:
#     $ nano /etc/ansible/hosts
#   2. Update the config-m2.env file to add platform-specific values
#   3. Run this command to remove Magento 2:
#     $ ansible-playbook remove-m2.yml
#
---
- hosts: m2
  tasks:
  - name: copy config-m2.env
    copy:
      src: ../config-m2.env
      dest: /root/config-m2.env
  - name: remove magento 2
    script: remove-magento2.sh